Added detekt and Gradle version catalog
connektions/android_app pull request #1
Opened 2023-05-24 19:38 UTC by ArtemZolotukh1n

Сорри за создание новой репы - в той проект был сделан на старой версии AS - и у меня много проблем с этим было. Пока оставлю ее - через дня два удалю.

2023-05-25 09:57 UTC, kpkpkpk requested changes

2023-05-25 09:57 UTC, kpkpkpk commented on app/build.gradle
> +    debugImplementation "androidx.compose.ui:ui-test-manifest:$compose_version"
тоже можно вынести зависимости в toml

2023-05-25 09:57 UTC, kpkpkpk commented on app/src/main/java/com/example/connektions/ui/theme/Color.kt
> +@file:Suppress("MagicNumber", "NewLineAtEndOfFile")
NewLineAtEndOfFile фиксится Editor -> General -> Ensure line feed at file end on Save

2023-05-25 09:57 UTC, kpkpkpk commented on app/src/main/java/com/example/connektions/ui/theme/Color.kt
> +@file:Suppress("MagicNumber", "NewLineAtEndOfFile")
плюс у тебя ./gradlew detekt должен по идее сам это поправлять

2023-05-25 09:57 UTC, kpkpkpk commented on build.gradle
> +subprojects{
ctrl + shift + l прожми, чтобы применилось форматирование

2023-05-25 09:57 UTC, kpkpkpk commented on buildscripts/detekt.gradle
> +detekt {
а, все, я понял, почему у тебя не работает автоформатирование детекта. тебе надо в build.gradle в dependencies добавить detektFormatting и detektPlugin: 

 dependencies {
    detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:[version]")
}

2023-05-25 09:57 UTC, kpkpkpk commented on buildscripts/detekt.gradle
> +detekt {
https://github.com/detekt/detekt

2023-05-25 09:57 UTC, kpkpkpk commented on app/src/main/java/com/example/connektions/ui/theme/Shape.kt
> +@file:Suppress( "NewLineAtEndOfFile")
в общем добавь автоформатирование детектом и включи настройку в студии и больше не саппрессь такое. Если оно подсвечивает - значит так надо (не всегда это правда, но на данном этапе это так)

2023-05-25 09:58 UTC, kpkpkpk commented
подробнее зачем надо использовать new line 
https://semakin.dev/2020/05/no_newline_at_end_of_file/

2023-05-25 10:01 UTC, kpkpkpk commented
и это, покажите дизайны, приложение должно быть красивым)
https://coursehunter.net/book/kniga-refactoring-ui-complete-package-video

2023-05-25 10:14 UTC, kpkpkpk requested changes

2023-05-25 10:14 UTC, kpkpkpk commented on app/src/main/java/com/example/connektions/data/repository/about.txt
> +Здесь хранятся классы репозиториев. Репозитории используются для обращения к источникам данных -
обычно такое не указывают, из названия пакетов и так понятно, для чего это служит

2023-05-25 10:14 UTC, kpkpkpk commented on app/src/main/java/com/example/connektions/data/model/about.txt
> + Здесь хранятся все классы моделей, которые представляют данные, которые вы будете
обычно такое не указывают, из названия пакетов и так понятно, для чего это служит

2023-05-25 10:32 UTC, ArtemZolotukh1n commented on app/src/main/java/com/example/connektions/data/repository/about.txt
> +Здесь хранятся классы репозиториев. Репозитории используются для обращения к источникам данных -
Просто ребята некоторые никогда с архитектурами не работали - думал может такие напоминалки будут им полезны

2023-05-25 11:01 UTC, ArtemZolotukh1n commented
> и это, покажите дизайны, приложение должно быть красивым) https://coursehunter.net/book/kniga-refactoring-ui-complete-package-video

Только по премиум подписке

2023-05-26 07:08 UTC, kpkpkpk commented on app/src/main/java/com/example/connektions/data/repository/about.txt
> +Здесь хранятся классы репозиториев. Репозитории используются для обращения к источникам данных -
ну окей, давай тогда оставим пока что, можно оформить даже в md формате. 
хотя с другой стороны у тебя по файлам будет понятно, что где лежит

2023-05-26 07:16 UTC, kpkpkpk requested changes

2023-05-26 07:16 UTC, kpkpkpk commented on app/build.gradle
> +    detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:1.17.0")
так, это можно вынести в либсы и это должно лежать на уровне project, а не в app/

2023-05-26 07:17 UTC, kpkpkpk requested changes
.

2023-05-26 07:17 UTC, kpkpkpk commented on app/build.gradle
> +    detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:1.17.0")
https://github.com/kpkpkpk/OneOfTheProject/blob/main/build.gradle.kts

не могу найти в доке этот момент

2023-05-26 13:05 UTC, kpkpkpk commented
кста а зачем форкать репозиторий? его же можно просто склонировать к себе и спокойно действовать стратегией tbd (ну или что-то похожее на нее)

2023-05-28 12:50 UTC, merged